### ISSUE TITLE
Package 'tm.plugin.webmining' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/NaturalLanguageProcessing#5]
Package [tm.plugin.webmining](https://CRAN.R-project.org/package=tm.plugin.webmining) is currently listed in CRAN Task View [NaturalLanguageProcessing](https://CRAN.R-project.org/view=NaturalLanguageProcessing) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by fwild** [comment]
I have contacted the maintainer of tm and the maintainer of the tm.plugin.webmining package. tm and plugins are still being maintained, but I am awaiting answer from the webmining plugin package maintainer regarding his plans.

**Comment by zeileis** [comment]
Finally removed from the task view now.
